# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Less"
license = "MIT"
licenselink = "https://github.com/4ever9/less/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = ["blog"]
features = ["simple"]
min_version = "0.41.0"
siteCreated = 2020

[author]
  name = "Aiden X"
  homepage = "https://forever9.com"